revaturexyz/housingxyz

.azure/azureup.yaml
README.md

setup the project continuous integration configuration

---

.azure/azureup.yaml
.azure/terraformup.tf

setup the project infrastructure configuration

---

.azure/azureup.yaml
angular/package.json

fix code analysis trigger configuration

---

.azure/azureup.yaml
.azure/terraformup.tf
.docker/dockerup.yaml

setup the project deployment environment

---

angular/src/app/services/provider-service.service.ts
angular/src/app/services/room.service.ts
angular/src/models/address.ts
angular/src/models/amenity.ts
angular/src/models/complex.ts
angular/src/models/location.ts

force provider constructor, added some provider method service. Added constructor to Complex model

---

angular/src/app/services/provider-service.service.ts

Changed some remnant lets to consts, added one more hard coded complex for testing

---

angular/src/models/Amenity.ts
angular/src/models/amenity.ts
angular/src/models/room.ts

Modified room model to with address object and complex id

---

angular/src/app/services/room.service.ts
angular/src/models/room.ts

- values are hard-coded until we have a repository we can call methods from

First three methods of rooms service

---

angular/package-lock.json
angular/package.json
angular/src/app/app-routing.module.ts
angular/src/app/app.module.ts
angular/src/app/nav/nav.component.html
angular/src/app/room-details/room-details.component.html
angular/src/app/room-details/room-details.component.spec.ts
angular/src/app/room-details/room-details.component.ts
angular/src/app/services/provider-service.service.ts
angular/src/app/testing/dummyData.ts
angular/src/app/testing/mock/mock-api-service.ts
angular/src/app/update-room/update-room.component.html
angular/src/app/update-room/update-room.component.scss
angular/src/app/update-room/update-room.component.spec.ts
angular/src/app/update-room/update-room.component.ts

added functionality to, as a provider, select a complex to display all room associated with that complex

---

.azure/azureup.yaml

Tells SonarCloud the current branch update for broker branch

correcting SonarCloud branch

---

angular/src/app/room-details/room-details.component.html
angular/src/app/room-details/room-details.component.ts
angular/src/app/services/provider-service.service.ts
angular/src/app/services/room.service.ts
angular/src/app/update-room/update-room.component.html
angular/src/app/update-room/update-room.component.scss
angular/src/app/update-room/update-room.component.ts
angular/src/models/provider.ts

adding ability to edit a room from the room list

---

angular/src/models/address.spec.ts
angular/src/models/address.ts
angular/src/models/amenity.spec.ts
angular/src/models/amenity.ts
angular/src/models/complex.spec.ts
angular/src/models/complex.ts
angular/src/models/trainingcenter.spec.ts
angular/src/models/trainingcenter.ts

- add four new models to be used in implementation of add-room feature
- add four test classes, one for each of these moddels
- @escalonn 

will add new models and model tests for add-room feature

---

.azure/azureup.yaml

Added one additional line to housingxyz YAML file that runs a lint check.

adding nmp run lint into pipeline build stage.

---

.azure/azureup.yaml

1. separated "nmp test" step into three separate steps: "nmp install", "nmp lint", and "nmp test".
2. replaced "nmp run lint" with "npx ng lint" (typo in the commit message).
3. "nmp run test" changed to "nmp test".
4. changed "cd angular" to "workingDirectory: $(appDir)" & created job-scoped appDir variables argument.
5. fixed my incorrect YAML syntax around the "workingDirectory" option

adding lint to pipeline.

---

angular/src/app/add-room/add-room.component.html
angular/src/app/add-room/add-room.component.ts
angular/src/app/services/static-test-data.ts

Talk to my team lead and the back end to discuss the validation needed when adding a room

Added some validation to the addroom form

---

angular/src/app/add-room/add-room.component.html
angular/src/app/add-room/add-room.component.scss

the user will be able to redirect back to the home page after clicking on the submit button instead of the submit button

the user will be able to redirect back to the home page.

---

angular/src/app/add-room/add-room.component.html
angular/src/app/add-room/add-room.component.scss

Made some style changes to the add room buttons so that they look nicer and added some spacing, so the buttons are not so close together. I also changed the order of the buttons so the submit is always on the left and cancel is always on the right.

Made some styling changes to all the buttons

---

angular/src/app/add-room/add-room.component.html
angular/src/app/add-room/add-room.component.scss

I fixed the formatting of the add address form so it looks better.

Form for adding an address looks better

---

angular/src/app/add-room/add-room.component.html
angular/src/app/add-room/add-room.component.scss
angular/src/app/add-room/add-room.component.ts
angular/src/app/services/provider.service.ts
angular/src/app/services/room.service.ts
angular/src/app/services/static-test-data.ts
angular/src/interfaces/room.ts

- updated markup to update room based on two-way binding from the form
- added methods to add room component to help with updating room, namely for when multiple amenities are selected
- tweaks to the test data file made so that room is an empty object
- one or two styling changes, more to come
- passes ng lint

add room form working functionality

---

angular/src/app/add-room/add-room.component.html
angular/src/app/add-room/add-room.component.scss
angular/src/app/add-room/add-room.component.ts

Will and I used two way binding so that when the add address form in the addroom is used, the new address is saved in the database.

create a new address when the form in add-room is being submitted.

---

.gitignore
angular/src/app/services/maps.service.ts
angular/src/interfaces/maps/maps-details.ts
angular/src/interfaces/maps/maps-geo-location.ts
angular/src/interfaces/maps/maps-geometry.ts
angular/src/interfaces/maps/maps.ts

Added comments to maps and .vs to gitignore

Added comments to maps and .vs to gitignore

---

angular/src/app/add-complex/add-complex.component.html
angular/src/app/add-complex/add-complex.component.ts

- Lots of comments added so that future developers who inherit this code have an idea of what's going on.

Added additional comments.

---

.dockerignore

based on `npx gitignore-to-dockerignore`

normalize dockerignore to gitignore.

---

angular/src/app/add-complex/add-complex.component.html
angular/src/app/app.module.ts
angular/src/environments/environment.prod.ts
angular/src/environments/environment.ts
angular/src/index.html

Diff from `master` branch environment config minimized.
Fixed a misleading error message in add complex component.
Some useful endpoints for local development added commented-out.

Fix some console errors and cleanup environment config

---

room/src/Revature.Room.DataAccess/Repository.cs

Fixed bug in repository

---

complexService/ComplexService/ComplexServiceApi.csproj
complexService/ComplexService/Program.cs
complexService/ComplexService/TestClass.cs
complexService/ComplexService/appsettings.json
complexService/ComplexServiceDatabase/Class1.cs
complexService/ComplexServiceDatabase/ComplexServiceDatabase.csproj
complexService/ComplexServiceDatabase/ServiceDatabase.cs
complexService/ComplexServiceLogic/Class1.cs
complexService/ComplexServiceLogic/ComplexServiceLogic.csproj
complexService/ComplexServiceLogic/ServiceLogic.cs
complexService/XUnitTestProject3/XUnitTestProject3.csproj

adds logging

---

address/src/Revature.Address.Api/Revature.Address.Api.csproj
address/src/Revature.Address.DataAccess/DataAccess.cs
address/src/Revature.Address.DataAccess/Mapper.cs
address/src/Revature.Address.DataAccess/Revature.Address.DataAccess.csproj
address/src/Revature.Address.Lib/Revature.Address.Lib.csproj
address/src/Revature.Address.Tests/Revature.Address.Tests.csproj

updated address service  data access functionality

added  data access and mapper classes, installed ef.design nuget package

---

address/src/Revature.Address.Api/Controllers/AddressController.cs
address/src/Revature.Address.Api/Program.cs
address/src/Revature.Address.Api/Startup.cs
address/src/Revature.Address.DataAccess/Entities/AddressDbContext.cs

docker compose now works properly and  get and post are functional in the Address API

fixed password error

---

room/src/Revature.Room.Tests/Revature.Room.DataAccess.Tests/RepositoryTest.cs

#Updated Repository Tests
- @escalonn

Fixed repository tests

---

address/src/Revature.Address.Api/Controllers/AddressController.cs
address/src/Revature.Address.Api/Filters/GoogleAddressValidator.cs
address/src/Revature.Address.DataAccess/DataAccess.cs
address/src/Revature.Address.DataAccess/Interfaces/IDataAccess.cs
address/src/Revature.Address.Lib/Address.cs

added ability to delete addresses by id

added delete to address service

---

address/src/Revature.Address.Api/Controllers/AddressController.cs
address/src/Revature.Address.Api/Filters/GoogleAddressValidator.cs

small fix to allow others to run current version of address service

fixed post function parameter

---

account/.azure/azureup.yaml
address/.azure/azureup.yaml
complex/.azure/azureup.yaml
housing/.azure/azureup.yaml
room/.azure/azureup.yaml
tenant/.azure/azureup.yaml

Update to azure pipes to include paths for pr's

---

room/src/Revature.Room.Tests/Revature.Room.Api.Tests/ComplexControllerTests.cs
room/src/Revature.Room.Tests/Revature.Room.Api.Tests/TenantControllerTests.cs
room/src/Revature.Room.Tests/Revature.Room.DataAccess.Tests/RepositoryTest.cs

Added TenantController Test

---

room/src/Revature.Room.Api/Controllers/ComplexController.cs
room/src/Revature.Room.Tests/Revature.Room.Api.Tests/ServiceBusTests.cs
room/src/Revature.Room.Tests/Revature.Room.DataAccess.Tests/RepositoryTest.cs

Added a repository test for GetFilteredRoomsAsync, Service Bus Test is empty AKA a work in progress
- @escalonn

Tri service bus test

---

tenant/src/Revature.Tenant.Tests/DataTests/TenantRoomRepositoryTest.cs

ok to go: TenantRoomRepositoryTest added.

---

tenant/src/Revature.Tenant.DataAccess/Repository/TenantRoomRepository.cs
tenant/src/Revature.Tenant.Lib/Interface/ITenantRoomRepository.cs
tenant/src/Revature.Tenant.Tests/DataTests/TenantRoomRepositoryTest.cs

- Added repository and method that returns occupants' information given a room Id.
- @escalonn

Tenant Service Progress of Marielle's Team

---

tenant/src/Revature.Tenant.DataAccess/Repository/TenantRoomRepository.cs
tenant/src/Revature.Tenant.Lib/Models/RoomInfo.cs
tenant/src/Revature.Tenant.Tests/LibTests/RoomInfoTest.cs

- Added room info model to hold necessary information for sorting the rooms by priority.
- @escalonn

Tenant service progress

---

room/src/Revature.Room.Api/Services/ServiceBusConsumer.cs
room/src/Revature.Room.Api/Services/ServiceBusSender.cs
room/src/Revature.Room.Api/Startup.cs
room/src/Revature.Room.Api/appsettings.json
room/src/Revature.Room.sln

- Added service bus endpoints to appsettings.Development.json. Service bus works.  
- @escalonn

Room service progress

---

tenant/src/Revature.Tenant.Tests/ApiTests/ControllerTests/TenantRoomControllerTests.cs
tenant/src/Revature.Tenant.Tests/DataTests/TenantRoomRepositoryTest.cs

added TenantRoomRepoTest and TenantRoomControllerTests

---

address/src/Revature.Address.Api/Controllers/AddressController.cs
address/src/Revature.Address.Api/Models/AddressModel.cs
address/src/Revature.Address.Api/Program.cs
address/src/Revature.Address.Api/Revature.Address.Api.csproj
address/src/Revature.Address.Api/Startup.cs
address/src/Revature.Address.DataAccess/DataAccess.cs
address/src/Revature.Address.Lib/BusinessLogic/AddressLogic.cs
address/src/Revature.Address.Lib/BusinessLogic/IAddressLogic.cs
address/src/Revature.Address.Lib/Models/Address.cs

added address controller and documentation for controller methods and fixed exception logging

added API functions to address service

---

address/src/Revature.Address.Api/Controllers/AddressController.cs

fixed checkdistance controller method

---

account/src/Revature.Account.Api/Controllers/CoordinatorAccountController.cs
account/src/Revature.Account.DataAccess/AccountDbContext.cs

Fixes a bug wherein a coordinator account is automatically created but throws an exception because required values are not supplied.
- @escalonn

Fixed db bug when adding new coordinator.

---

authInstructions.cs

Some additions to the auth instructions to make them more complete.
- @escalonn

Update auth instructions.

---

address/src/Revature.Address.Tests/Api.Tests/ControllerTests.cs

added tests for controller
